stcCallback1001({
	"totalCount" : "6679",
	"topics" : [
			{
				"title" : "XTemplate with in EditorGridPanel",
				"threadid" : "133690",
				"username" : "kpr@emco",
				"userid" : "272497",
				"dateline" : "1305604761",
				"postid" : "602876",
				"forumtitle" : "Ext 3.x: Help",
				"forumid" : "40",
				"replycount" : "2",
				"lastpost" : "1305857807",
				"lastposter" : "kpr@emco",
				"excerpt" : "Hi , \n \nI have an EditiorGridPanel whose one column i am using XTemplate to render and another Column is Combo Box Field .\nWhen i render the EditorGri..."
			},
			{
				"title" : "IFrame error  &quot;_flyweights is undefined&quot;",
				"threadid" : "133571",
				"username" : "Daz",
				"userid" : "52119",
				"dateline" : "1305533577",
				"postid" : "602456",
				"forumtitle" : "Ext 3.x: Help",
				"forumid" : "40",
				"replycount" : "1",
				"lastpost" : "1305857313",
				"lastposter" : "Daz",
				"excerpt" : "For Ext 3.3.0 using Firefox 4 & Firebug, the following error is often happening when our app loads:\n    \"e._flyweights is undefined\".\n   \n  Yet, this ..."
			},
			{
				"title" : "Status bar error with IFrames",
				"threadid" : "134120",
				"username" : "Daz",
				"userid" : "52119",
				"dateline" : "1305857168",
				"postid" : "604220",
				"forumtitle" : "Ext 3.x: Bugs",
				"forumid" : "41",
				"replycount" : "0",
				"lastpost" : "1305857168",
				"lastposter" : "Daz",
				"excerpt" : "Ext version tested:\n\n Ext 3.3.3\n\nAdapter used:\next\n \ncss used:\ndefault ext-all.css\n \nBrowser versions tested against:\nFF4 (firebug 1.7.1 installed)\n \n..."
			},
			{
				"title" : "hellllllllllllllp,why it doesn't fire cellclick event after I change the cell value??",
				"threadid" : "133827",
				"username" : "aimer311",
				"userid" : "162000",
				"dateline" : "1305700219",
				"postid" : "603309",
				"forumtitle" : "Ext 3.x: Help",
				"forumid" : "40",
				"replycount" : "3",
				"lastpost" : "1305856996",
				"lastposter" : "aimer311",
				"excerpt" : "ok,I will discribe this problem as more detail as I can,I look into this problem for a whole day.\r\nI set clicksToEdit=1 to a EditorGridPanel,so when I..."
			},
			{
				"title" : "Extjs 4.0 support for IE9",
				"threadid" : "122352",
				"username" : "extdev22",
				"userid" : "48017",
				"dateline" : "1296097557",
				"postid" : "565503",
				"forumtitle" : "Ext: Open Discussion",
				"forumid" : "6",
				"replycount" : "30",
				"lastpost" : "1305841535",
				"lastposter" : "edspencer",
				"excerpt" : "Hi, does Extjs 4.0 will fully support IE9? in other words if application developed in Extjs 4.0 and tested using IE9 is there anything expected to be ..."
			},
			{
				"title" : "Using XTemplate to send XML",
				"threadid" : "134102",
				"username" : "cayenne_08",
				"userid" : "237393",
				"dateline" : "1305841170",
				"postid" : "604153",
				"forumtitle" : "Ext 3.x: Help",
				"forumid" : "40",
				"replycount" : "0",
				"lastpost" : "1305841170",
				"lastposter" : "cayenne_08",
				"excerpt" : "This is what I am trying to do to post custom XML on editor form submit:\r\n\r\n\n\r\n(function() {\r\n      Q.dxi.QXmlWriter = Ext.extend(Ext.data.XmlWriter, ..."
			},
			{
				"title" : "Open Source Development - The people you interact with....",
				"threadid" : "134093",
				"username" : "watrboy00",
				"userid" : "9862",
				"dateline" : "1305837814",
				"postid" : "604114",
				"forumtitle" : "Community Discussion",
				"forumid" : "68",
				"replycount" : "0",
				"lastpost" : "1305837814",
				"lastposter" : "watrboy00",
				"excerpt" : "Wanted to share a good article related to open source development and the shades of people you might interact with...\r\n\r\nEnjoy!\r\n\r\nhttp:\/\/goo.gl\/BwDaF"
			},
			{
				"title" : "What widgets are missing most in the ExtJs library?",
				"threadid" : "134091",
				"username" : "Andrew.Golik",
				"userid" : "32056",
				"dateline" : "1305837033",
				"postid" : "604102",
				"forumtitle" : "Community Discussion",
				"forumid" : "68",
				"replycount" : "0",
				"lastpost" : "1305837033",
				"lastposter" : "Andrew.Golik",
				"excerpt" : "What are the most missed widgets in ExtJs library?\r\nI really like the ExtJs library but I feel like there is gap between jQuery and ExtJs libraries in..."
			},
			{
				"title" : "What widgets are missing most in the ExtJs library?",
				"threadid" : "134090",
				"username" : "Andrew.Golik",
				"userid" : "32056",
				"dateline" : "1305836975",
				"postid" : "604100",
				"forumtitle" : "Community Discussion",
				"forumid" : "68",
				"replycount" : "0",
				"lastpost" : "1305836975",
				"lastposter" : "Andrew.Golik",
				"excerpt" : "What are the most missed widgets in ExtJs library?\r\nI really like the ExtJs library but I feel like there is gap between jQuery and ExtJs libraries in..."
			},
			{
				"title" : "What widgets are missing most in the ExtJs library?",
				"threadid" : "134089",
				"username" : "Andrew.Golik",
				"userid" : "32056",
				"dateline" : "1305836900",
				"postid" : "604099",
				"forumtitle" : "Community Discussion",
				"forumid" : "68",
				"replycount" : "0",
				"lastpost" : "1305836900",
				"lastposter" : "Andrew.Golik",
				"excerpt" : "What are the most missed widgets in ExtJs library?\r\nI really like the ExtJs library but I feel like there is gap between jQuery and ExtJs libraries in..."
			},
			{
				"title" : "GridPanel Scroll doesn't work",
				"threadid" : "134088",
				"username" : "daniel_",
				"userid" : "268152",
				"dateline" : "1305836704",
				"postid" : "604097",
				"forumtitle" : "Ext 3.x: Help",
				"forumid" : "40",
				"replycount" : "0",
				"lastpost" : "1305836704",
				"lastposter" : "daniel_",
				"excerpt" : "hello\n\nAutoScroll doesn't work with the gridPanel. if i specify a specific height and the content is bigger i get just the name of the columns\n26148 (..."
			},
			{
				"title" : "Expand child node in tree after context menu click",
				"threadid" : "134084",
				"username" : "TheBigOnion",
				"userid" : "108877",
				"dateline" : "1305835440",
				"postid" : "604088",
				"forumtitle" : "Ext 3.x: Help",
				"forumid" : "40",
				"replycount" : "0",
				"lastpost" : "1305835440",
				"lastposter" : "TheBigOnion",
				"excerpt" : "Hello all,\n I am trying to expand a child node in a tree after I reload it.  The only information I have when I click the context menu is the node url..."
			},
			{
				"title" : "ItemSelector issue",
				"threadid" : "134083",
				"username" : "yga",
				"userid" : "90363",
				"dateline" : "1305835064",
				"postid" : "604086",
				"forumtitle" : "Ext 3.x: Help",
				"forumid" : "40",
				"replycount" : "0",
				"lastpost" : "1305835064",
				"lastposter" : "yga",
				"excerpt" : "Selected item in left pane wont show correctly in rigth pane\n\nCODE:\nvar dataRecordCentroP = new Ext.data.Record.create([\n                             ..."
			},
			{
				"title" : "Dynamically add item to viewport region",
				"threadid" : "134080",
				"username" : "FoobarusMaximus",
				"userid" : "271630",
				"dateline" : "1305834734",
				"postid" : "604083",
				"forumtitle" : "Ext: Open Discussion",
				"forumid" : "6",
				"replycount" : "0",
				"lastpost" : "1305834734",
				"lastposter" : "FoobarusMaximus",
				"excerpt" : "Let's say I have a JS in one file that creates a `Viewport`:\n\n\n    Ext.create('Ext.container.Viewport', {\n        layout: 'border',\n        items: [\n ..."
			},
			{
				"title" : "Add Text to the current cursor-position in a textarea",
				"threadid" : "133836",
				"username" : "vitalka",
				"userid" : "263964",
				"dateline" : "1305706310",
				"postid" : "603335",
				"forumtitle" : "Ext 3.x: Help",
				"forumid" : "40",
				"replycount" : "1",
				"lastpost" : "1305831679",
				"lastposter" : "keckeroo",
				"excerpt" : "Hi, I googled about hour and nothing... Please help me I have code:\n\n\n            { \n                fieldLabel        : scaffoldPanel.labels['oki[tex..."
			},
			{
				"title" : "Extending Panel which is built upon store ...",
				"threadid" : "134068",
				"username" : "keckeroo",
				"userid" : "30160",
				"dateline" : "1305829513",
				"postid" : "604047",
				"forumtitle" : "Ext 3.x: Help",
				"forumid" : "40",
				"replycount" : "0",
				"lastpost" : "1305829513",
				"lastposter" : "keckeroo",
				"excerpt" : "I would like to 'build' a panel (extend) that has a store associated with it - I was wondering if anyone had any insight as to how to 'delay' the crea..."
			},
			{
				"title" : "programming problem",
				"threadid" : "134050",
				"username" : "flamant",
				"userid" : "165442",
				"dateline" : "1305823292",
				"postid" : "603981",
				"forumtitle" : "Ext 3.x: Help",
				"forumid" : "40",
				"replycount" : "4",
				"lastpost" : "1305827367",
				"lastposter" : "flamant",
				"excerpt" : "Hi,\n I am wondering if when we have  config option property that has not a setter method we can change it dynamically.\n\nFor example ComboBox has a all..."
			},
			{
				"title" : "Sencha web site extremely slow",
				"threadid" : "133003",
				"username" : "cgi-bin",
				"userid" : "3273",
				"dateline" : "1305041059",
				"postid" : "600490",
				"forumtitle" : "Ext: Open Discussion",
				"forumid" : "6",
				"replycount" : "28",
				"lastpost" : "1305827236",
				"lastposter" : "mberrie",
				"excerpt" : "Ever since since the release of 4.0 the sencha web site has been getting slower and slower to respond. Today has been particularly bad, as the API doc..."
			},
			{
				"title" : "Pivot table",
				"threadid" : "133872",
				"username" : "christophe67",
				"userid" : "51617",
				"dateline" : "1305729765",
				"postid" : "603413",
				"forumtitle" : "Ext 3.x: Help",
				"forumid" : "40",
				"replycount" : "4",
				"lastpost" : "1305826171",
				"lastposter" : "fay",
				"excerpt" : "Hello,\n\nI need to build a pivot table, but the header and the left axis doesn't show.\nCan anybody help me, I don't what is wrong in my code.\n\n\n    var..."
			},
			{
				"title" : "Scroll bars in ext js tool tips",
				"threadid" : "133897",
				"username" : "sanjay_1985",
				"userid" : "71157",
				"dateline" : "1305742780",
				"postid" : "603477",
				"forumtitle" : "Ext 3.x: Help",
				"forumid" : "40",
				"replycount" : "1",
				"lastpost" : "1305825686",
				"lastposter" : "friend",
				"excerpt" : "Hi,\nCan anyone tell me how to bring scroll bars in tool tips.We have huge contents to be displayed in tool tip.\n \nThanks,\nSanjay"
			},
			{
				"title" : "POSTING XML sub-class",
				"threadid" : "134057",
				"username" : "cayenne_08",
				"userid" : "237393",
				"dateline" : "1305825617",
				"postid" : "604009",
				"forumtitle" : "Ext: Open Discussion",
				"forumid" : "6",
				"replycount" : "0",
				"lastpost" : "1305825617",
				"lastposter" : "cayenne_08",
				"excerpt" : "We need a way to post xml with different elements to the server from a single form.\r\n\r\nSo for instance, we want to use the same form to POST something..."
			},
			{
				"title" : "Help POST parameter from Ext.form to PHP",
				"threadid" : "134049",
				"username" : "Gusti",
				"userid" : "273373",
				"dateline" : "1305823237",
				"postid" : "603980",
				"forumtitle" : "Ext 3.x: Help",
				"forumid" : "40",
				"replycount" : "2",
				"lastpost" : "1305825489",
				"lastposter" : "Gusti",
				"excerpt" : "Hi all.. I'm new to ExtJS, and currently i'm using Ext JS 3.0.\nI'm using Ext.chart.LineChart to show graph data from date range.\nThis is my graph :\n26..."
			},
			{
				"title" : "Problem for rendering a filter list in context menu",
				"threadid" : "133923",
				"username" : "mfrancey",
				"userid" : "23964",
				"dateline" : "1305754701",
				"postid" : "603551",
				"forumtitle" : "Ext 3.x: Help",
				"forumid" : "40",
				"replycount" : "1",
				"lastpost" : "1305825106",
				"lastposter" : "friend",
				"excerpt" : "Hi,\n\n\n\n I have a grid in a viewport.\n The viewport is rendered into body\n\n... \nrenderTo:Ext.getBody()\n...\n In one of my grid column, I use a filter (t..."
			},
			{
				"title" : "DisplayField format problem",
				"threadid" : "133999",
				"username" : "veerai2i",
				"userid" : "103140",
				"dateline" : "1305804094",
				"postid" : "603794",
				"forumtitle" : "Ext 3.x: Help",
				"forumid" : "40",
				"replycount" : "3",
				"lastpost" : "1305824386",
				"lastposter" : "friend",
				"excerpt" : "Hi ,\n\ni am adding displayfield and its coming nicely, but the original alignment is missing, the same thing in textarea working fine.\nIn displayField ..."
			},
			{
				"title" : "the combo fire the trigger event and the change event when I fire a keymap event",
				"threadid" : "134035",
				"username" : "flamant",
				"userid" : "165442",
				"dateline" : "1305816817",
				"postid" : "603915",
				"forumtitle" : "Ext 3.x: Help",
				"forumid" : "40",
				"replycount" : "1",
				"lastpost" : "1305824146",
				"lastposter" : "friend",
				"excerpt" : "Hi,\nI put a keymap on a combo :\n\n\n\n        new Ext.KeyMap(field.getId(),\n            [{\n                key: 'a',\n                ctrl: true,\n        ..."
			} ]
});