#db table name
#I can don't config table name,but it not more readable than this way
tableName=Mig_Auditf_Main
#pojo name
pojoName=MigAuditfMain
#table chinese name
tableName_zh=\u5B57\u6BB5\u7A3D\u6838\u9879\u914D\u7F6E\u8868

# primary key
primaryKeyColumnName=PROCESS_ID
# primary key sequence name 
primaryKeySequence=SEQ_MIG_JOB_PROCESS_ID

# excel file name
export.fileName=\u63A7\u4EF6\u6A21\u677F
# excel sheet name
export.sheetName=\u63A7\u4EF6\u6A21\u677F
#export configuration
# fixed column count range:0~columnCount, recomend 0~4,the column start at this first and obey the original order
export.fixColumnCount=3

# whether office excel file's sheet autoSizeColumn ,if data hurge care and suggest set false
export.sheetAutoSizeColumn=true
# if the export file compressed, value:  true/false
export.compress=false

# singleFileRecordSize>=singleSheetRecordSize 
# the max record size of single excel sheet , range :1~65534, one row remain for column label
export.singleSheetRecordSize=50000

# the max record size of single excel file , the max size is depend on the one row data size, 150000 is recommend
export.singleFileRecordSize=150000

export.level1MinCount=10000
export.level2MinCount=50000
export.level3MinCount=100000

#export data mode. value scope: true- synchronous / false - asynchronous
export.synchronous=true
#The maximum number of threads ,use of export data file
export.maxThreadNumber=4
#export data file timeout ,if overstepping the time limit ,program auto close, unit: millisecond ,eg: 5 * 60 * 60 * 1000=5hours
export.timeout=1 * 60 * 1000