package person.daizhongde.migration.spring.service.wsclient.cominterface;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2015-07-20T16:18:31.626+08:00
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://10.1.249.109:1111/migration/ComInterFace.wsdl", name = "ComInterFacePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ComInterFacePortType {

    /**
     * Service definition of function ns2__LoadData
     */
    @WebResult(name = "retMsg", targetNamespace = "")
    @RequestWrapper(localName = "LoadData", targetNamespace = "urn:ComInterFace", className = "person.daizhongde.migration.spring.service.wsclient.cominterface.LoadData")
    @WebMethod(operationName = "LoadData")
    @ResponseWrapper(localName = "LoadDataResponse", targetNamespace = "urn:ComInterFace", className = "person.daizhongde.migration.spring.service.wsclient.cominterface.LoadDataResponse")
    public java.lang.String loadData(
        @WebParam(name = "szMsg", targetNamespace = "")
        person.daizhongde.migration.spring.service.wsclient.cominterface.LOADDATACONFIG szMsg
    );

    /**
     * Service definition of function ns2__OutDataBase
     */
    @WebResult(name = "retMsg", targetNamespace = "")
    @RequestWrapper(localName = "OutDataBase", targetNamespace = "urn:ComInterFace", className = "person.daizhongde.migration.spring.service.wsclient.cominterface.OutDataBase")
    @WebMethod(operationName = "OutDataBase")
    @ResponseWrapper(localName = "OutDataBaseResponse", targetNamespace = "urn:ComInterFace", className = "person.daizhongde.migration.spring.service.wsclient.cominterface.OutDataBaseResponse")
    public java.lang.String outDataBase(
        @WebParam(name = "szMsg", targetNamespace = "")
        person.daizhongde.migration.spring.service.wsclient.cominterface.OUTDATABASECONFIG szMsg
    );

    /**
     * Service definition of function ns2__Controller
     */
    @WebResult(name = "retMsg", targetNamespace = "")
    @RequestWrapper(localName = "Controller", targetNamespace = "urn:ComInterFace", className = "person.daizhongde.migration.spring.service.wsclient.cominterface.Controller")
    @WebMethod(operationName = "Controller")
    @ResponseWrapper(localName = "ControllerResponse", targetNamespace = "urn:ComInterFace", className = "person.daizhongde.migration.spring.service.wsclient.cominterface.ControllerResponse")
    public java.lang.String controller(
        @WebParam(name = "szMsg", targetNamespace = "")
        person.daizhongde.migration.spring.service.wsclient.cominterface.CONTROLSIGNAL szMsg
    );

    /**
     * Service definition of function ns2__LegalityAudit
     */
    @WebResult(name = "retMsg", targetNamespace = "")
    @RequestWrapper(localName = "LegalityAudit", targetNamespace = "urn:ComInterFace", className = "person.daizhongde.migration.spring.service.wsclient.cominterface.LegalityAudit")
    @WebMethod(operationName = "LegalityAudit")
    @ResponseWrapper(localName = "LegalityAuditResponse", targetNamespace = "urn:ComInterFace", className = "person.daizhongde.migration.spring.service.wsclient.cominterface.LegalityAuditResponse")
    public java.lang.String legalityAudit(
        @WebParam(name = "szMsg", targetNamespace = "")
        person.daizhongde.migration.spring.service.wsclient.cominterface.AUDITDATACONFIG szMsg
    );

    /**
     * Service definition of function ns2__SplitFile
     */
    @WebResult(name = "retMsg", targetNamespace = "")
    @RequestWrapper(localName = "SplitFile", targetNamespace = "urn:ComInterFace", className = "person.daizhongde.migration.spring.service.wsclient.cominterface.SplitFile")
    @WebMethod(operationName = "SplitFile")
    @ResponseWrapper(localName = "SplitFileResponse", targetNamespace = "urn:ComInterFace", className = "person.daizhongde.migration.spring.service.wsclient.cominterface.SplitFileResponse")
    public java.lang.String splitFile(
        @WebParam(name = "szMsg", targetNamespace = "")
        person.daizhongde.migration.spring.service.wsclient.cominterface.SPLITCONFIG szMsg
    );

    /**
     * Service definition of function ns2__OutDataFile
     */
    @WebResult(name = "retMsg", targetNamespace = "")
    @RequestWrapper(localName = "OutDataFile", targetNamespace = "urn:ComInterFace", className = "person.daizhongde.migration.spring.service.wsclient.cominterface.OutDataFile")
    @WebMethod(operationName = "OutDataFile")
    @ResponseWrapper(localName = "OutDataFileResponse", targetNamespace = "urn:ComInterFace", className = "person.daizhongde.migration.spring.service.wsclient.cominterface.OutDataFileResponse")
    public java.lang.String outDataFile(
        @WebParam(name = "szMsg", targetNamespace = "")
        person.daizhongde.migration.spring.service.wsclient.cominterface.OUTDATAFILECONFIG szMsg
    );

    /**
     * Service definition of function ns2__ExecuteSql
     */
    @WebResult(name = "retMsg", targetNamespace = "")
    @RequestWrapper(localName = "ExecuteSql", targetNamespace = "urn:ComInterFace", className = "person.daizhongde.migration.spring.service.wsclient.cominterface.ExecuteSql")
    @WebMethod(operationName = "ExecuteSql")
    @ResponseWrapper(localName = "ExecuteSqlResponse", targetNamespace = "urn:ComInterFace", className = "person.daizhongde.migration.spring.service.wsclient.cominterface.ExecuteSqlResponse")
    public java.lang.String executeSql(
        @WebParam(name = "szMsg", targetNamespace = "")
        person.daizhongde.migration.spring.service.wsclient.cominterface.EXCUTESQLCONFIG szMsg
    );

    /**
     * Service definition of function ns2__ExeLinuxBin
     */
    @WebResult(name = "retMsg", targetNamespace = "")
    @RequestWrapper(localName = "ExeLinuxBin", targetNamespace = "urn:ComInterFace", className = "person.daizhongde.migration.spring.service.wsclient.cominterface.ExeLinuxBin")
    @WebMethod(operationName = "ExeLinuxBin")
    @ResponseWrapper(localName = "ExeLinuxBinResponse", targetNamespace = "urn:ComInterFace", className = "person.daizhongde.migration.spring.service.wsclient.cominterface.ExeLinuxBinResponse")
    public java.lang.String exeLinuxBin(
        @WebParam(name = "szMsg", targetNamespace = "")
        person.daizhongde.migration.spring.service.wsclient.cominterface.EXELINUXBINCONFIG szMsg
    );

    /**
     * Service definition of function ns2__ConsistencyAudit
     */
    @WebResult(name = "retMsg", targetNamespace = "")
    @RequestWrapper(localName = "ConsistencyAudit", targetNamespace = "urn:ComInterFace", className = "person.daizhongde.migration.spring.service.wsclient.cominterface.ConsistencyAudit")
    @WebMethod(operationName = "ConsistencyAudit")
    @ResponseWrapper(localName = "ConsistencyAuditResponse", targetNamespace = "urn:ComInterFace", className = "person.daizhongde.migration.spring.service.wsclient.cominterface.ConsistencyAuditResponse")
    public java.lang.String consistencyAudit(
        @WebParam(name = "szMsg", targetNamespace = "")
        person.daizhongde.migration.spring.service.wsclient.cominterface.CONSISTENCYAUDITCONFIG szMsg
    );

    /**
     * Service definition of function ns2__FieldAudit
     */
    @WebResult(name = "retMsg", targetNamespace = "")
    @RequestWrapper(localName = "FieldAudit", targetNamespace = "urn:ComInterFace", className = "person.daizhongde.migration.spring.service.wsclient.cominterface.FieldAudit")
    @WebMethod(operationName = "FieldAudit")
    @ResponseWrapper(localName = "FieldAuditResponse", targetNamespace = "urn:ComInterFace", className = "person.daizhongde.migration.spring.service.wsclient.cominterface.FieldAuditResponse")
    public java.lang.String fieldAudit(
        @WebParam(name = "szMsg", targetNamespace = "")
        person.daizhongde.migration.spring.service.wsclient.cominterface.FIELDAUDITCONFIG szMsg
    );
}
