package person.daizhongde.migration.spring.service.wsclient.cominterface;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import org.slf4j.LoggerFactory;

import javax.xml.ws.Service;

/**
 * gSOAP 2.8.17r generated service definition
 *
 * This class was generated by Apache CXF 3.0.2
 * 2015-07-20T16:18:31.670+08:00
 * Generated source version: 3.0.2
 * 
 */
@WebServiceClient(name = "ComInterFace", 
                  wsdlLocation = "http://10.1.249.109:1111/migration/ComInterFace?wsdl",
                  targetNamespace = "http://10.1.249.109:1111/migration/ComInterFace.wsdl") 
public class ComInterFace extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://10.1.249.109:1111/migration/ComInterFace.wsdl", "ComInterFace");
    public final static QName ComInterFace = new QName("http://10.1.249.109:1111/migration/ComInterFace.wsdl", "ComInterFace");
    static {
        URL url = null;
        try {
            url = new URL("http://10.1.249.109:1111/migration/ComInterFace?wsdl");
        } catch (MalformedURLException e) {
            LoggerFactory.getLogger(ComInterFace.class.getName())
                .error("Can not initialize the default wsdl from {0}", "http://10.1.249.109:1111/migration/ComInterFace?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ComInterFace(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ComInterFace(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ComInterFace() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ComInterFace(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ComInterFace(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ComInterFace(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns ComInterFacePortType
     */
    @WebEndpoint(name = "ComInterFace")
    public ComInterFacePortType getComInterFace() {
        return super.getPort(ComInterFace, ComInterFacePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ComInterFacePortType
     */
    @WebEndpoint(name = "ComInterFace")
    public ComInterFacePortType getComInterFace(WebServiceFeature... features) {
        return super.getPort(ComInterFace, ComInterFacePortType.class, features);
    }

}
