maven.datasource.url=jdbc\:mysql\://localhost\:3306/tool?charset\=utf-8
maven.datasource.username=root
maven.datasource.password=123
maven.log4j2.log_home=D\:/usr/migration/logs/
maven.REST.URI=http\://localhost\:1111/migration/