maven.datasource.url=jdbc\:mysql\://rm-wz92qg5g95kqq74xto.mysql.rds.aliyuncs.com\:3306/tool?charset\=utf-8&useSSL=true
maven.datasource.username=root
maven.datasource.password=nStamp_2017
maven.log4j2.log_home=/home/stamp/app/tomcat8090/logs/copote_oa/
maven.REST.URI=http\://localhost\:1111/migration/

#maven.datasource.url=jdbc\:mysql\://10.158.240.7\:3306/tool?charset\=utf-8
#maven.datasource.username=hadoop
#maven.datasource.password=hadoop
#maven.log4j2.log_home=/mnt/disk01/.hadoopadmin/app/migration/logs/
#maven.REST.URI=http\://10.158.240.9\:1111/migration/