maven.datasource.url=jdbc\:mysql\://192.168.2.100\:3306/tool?charset\=utf-8
maven.datasource.username=root
maven.datasource.password=root
maven.log4j2.log_home=/home/yzpp/logs/migration/
maven.REST.URI=http\://localhost\:1111/migration/

#maven.datasource.url=jdbc\:mysql\://10.158.240.7\:3306/tool?charset\=utf-8
#maven.datasource.username=hadoop
#maven.datasource.password=hadoop
#maven.log4j2.log_home=/mnt/disk01/.hadoopadmin/app/migration/logs/
#maven.REST.URI=http\://10.158.240.9\:1111/migration/