#globel export configuration

# excel file name
export.fileName=\u65B0\u5BFC\u51FA\u6587\u4EF6
# excel sheet name
export.sheetName=\u8868\u5355
# fixed column count range:0~columnCount, recomend 0~4,the column start at this first and obey the original order
export.fixColumnCount=3
# whether office excel file's sheet autoSizeColumn ,if data hurge care and suggest set false
export.sheetAutoSizeColumn=true
# if the export file compressed, value:  true/false
export.compress=false
# singleFileRecordSize>=singleSheetRecordSize 
# the max record size of single excel sheet , range :1~65534, one row remain for column label
export.singleSheetRecordSize=50000

# the max record size limit of single excel file , the max size is depend on the one row data size, 150000 is recommend
export.singleFileRecordSize=150000

# globel config, Can be customized
export.level1MinCount=10000
export.level2MinCount=50000
export.level3MinCount=100000

#export data mode. value scope: true- synchronous / false - asynchronous. Currently it is not used
export.synchronous=true
#The maximum number of threads ,use of export data file. Currently it is not used
export.maxThreadNumber=4
#export data file timeout ,if overstepping the time limit ,program auto close, unit: millisecond ,eg: 5 * 60 * 60 * 1000=5hours. Currently it is not used
export.timeout=1 * 60 * 1000
