#globel import configuration

# the max size limit of single excel file , 60MB is recommend, unit: Byte
import.singleFileMaxSize=60 * 1024 * 1024

# globel config, Can be customized. Unit is Byte
import.level1MinSize=5 * 1024 * 1024
import.level2MinSize=15 * 1024 * 1024
import.level3MinSize=30 * 1024 * 1024

#import data mode. value scope: true- synchronous / false - asynchronous. Currently it is not used
import.synchronous=true
#The maximum number of threads ,use of import data file. Currently it is not used
import.maxThreadNumber=4
#import data file timeout ,if overstepping the time limit ,program auto close, unit: millisecond ,eg: 5 * 60 * 60 * 1000=5hours  . Currently it is not used
import.timeout=1 * 60 * 1000