#production mode, develop mode. value;[true,false]
PRODUCTION_MODE=false

#whether project need login
LOGIN_CHECK=false

AUTH.schema=tool
AUTH.configFileDirectory=person/daizhongde/authority/config

COMMON.schema=tool
COMMON.configFileDirectory=person/daizhongde/migration/config

BUSI.schema=tool
# the program generated config file'loacation.
BUSI.configFileDirectory=person/daizhongde/migration/config

#datasource.jndi=java:comp/env/toolJNDI
datasource.driverClassName=com.mysql.jdbc.Driver

#datasource.url=jdbc\:mysql\://10.158.240.7\:3306/tool?charset\=utf-8
#datasource.username=hadoop
#datasource.password=hadoop
datasource.url=${maven.datasource.url}
datasource.username=${maven.datasource.username}
datasource.password=${maven.datasource.password}

##################  hibernate config  ##################
hibernate.dialect=org.hibernate.dialect.MySQLDialect
#hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
#hibernate.dialect=person.daizhongde.virtue.hibernate.ExtendedMySQLDialect
# hibernate.dialect=org.hibernate.dialect.MySQLInnoDBDialect
# hibernate.dialect=org.hibernate.dialect.MySQLMyISAMDialect
hibernate.show_sql=false
hibernate.format_sql=true

hibernate.connection.characterEncoding=UTF-8
hibernate.connection.useUnicode=true
hibernate.jdbc.use_scrollable_resultset=false


#whether downloadfile need login
download.login=false
##################  system  ##################
system.version=2.0

#default operator's index
defaultOperatorIndex=1
#if the bottom frame support setParameterList method
supportSetParameterList=true
# sugguest application deploy directory close
linux.localFileRootDirectory=/usr/migrationWebApp

windows.localFileRootDirectory=D\:/usr/migrationWebApp
#single job max thread number, invaild current
singleJobMaxThreadNum = 900
#job max thread number  AIDM:30   HadoopDataSync:3
maxThreadNum = 900

# the multiple of max record size of single excel file of txt file, 6 is recommend. Can't be customized
IE.txtMultiple=6

# Import and Export semaphore. globel config, Can't be customized
IE.level1SemaphoreCount=8
IE.level2SemaphoreCount=4
IE.level3SemaphoreCount=2

connextion.ip=10.226.4.233
connextion.port=3306
retail.ip=10.226.4.234
retail.port=3307

#sit.account=root/aliOS1688
sit.HIP=192.168.252.181
sit.MySQLPARAM=-h192.168.252.191 -P3306 -udrds_xydjy_cs -pXydjy1234
sit.DBNAME=drds_xydjy_cs

uat.HIP=10.3.106.109
uat.MySQLPARAM=-h10.3.106.181 -P3306 -udrds_xydjy_uat_app -pWc123456
uat.DBNAME=drds_xydjy_uat_app

# 10.4.230.89
prod.HIP=10.4.230.84
prod.MySQLPARAM=-h10.4.70.74 -P3306 -udrds_xydjy_sc_dbzx -pWc123456
prod.DBNAME=drds_xydjy_sc_dbzx

src.test.HIP=10.3.64.51
src.test.OraclePARAM=yzpp/yzpp@10.3.64.51:1521/yzpp

src.prod.HIP=10.3.64.13
src.prod.OraclePARAM=yzpp/yzpp@10.3.64.13:1521/yzpp/yzpp1


# imap will effect server mail, pop3 will not
# smtp 25   pop3  465
email.protocol=smtp
# smtp.qq.com   mail.hngytobacco.com smtp.exmail.qq.com
email.host=smtp.qq.com
# imap 25 cyprt465 or 587  pop3 110 cyprt995 
email.port=25
email.username=413881461@qq.com
# pop3/smtp ousimktwtmkpbjfj  413:kyhhowuvljumbiah
email.password=xjxrzuadrcqdbhjb
# imap zppeelwajfbkbjhf
email.auth=false
email.systemEmail=413881461@qq.com

email.taskErrorEmail=true
REST.URL=${maven.REST.URI}
