# DEBUG < INFO < WARN < ERROR < FATAL.
# Set root logger level to DEBUG and its only appender to A1.
### set log levels ###
log4j.rootLogger = INFO ,stdout ,  D ,  E

### output to the console ###
log4j.appender.stdout = org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target = System.out
log4j.appender.stdout.layout = org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern =%-5p %d{yyyy-MM-dd HH\:mm\:ss} [\u65E5\u5FD7\u4FE1\u606F] %m%n
#log4j.appender.stdout.layout.ConversionPattern =%d [%t] %-5p %c - %m%n

### output log file day by day  ###
log4j.appender.D = org.apache.log4j.DailyRollingFileAppender
log4j.appender.D.File = ${maven.log4j2.log_home}/log.log
#log4j.appender.D.File = /usr/authorityfile/logs/log.log
#log4j.appender.D.File = ${VirtueLog4j.root}/logs/log.log
log4j.appender.D.Append = true
log4j.appender.D.Threshold = INFO
log4j.appender.D.layout = org.apache.log4j.PatternLayout
log4j.appender.D.layout.ConversionPattern = %-d{yyyy-MM-dd HH:mm:ss}  [ %t:%r ] - [ %p ]  %m%n

### save error log single file ###
log4j.appender.E = org.apache.log4j.DailyRollingFileAppender
log4j.appender.E.File = ${maven.log4j2.log_home}/error.log
#log4j.appender.E.File = /usr/authorityfile/logs/error.log
#log4j.appender.E.File = ${VirtueLog4j.root}/logs/error.log
log4j.appender.E.Append = true
log4j.appender.E.Threshold = ERROR
log4j.appender.E.layout = org.apache.log4j.PatternLayout
log4j.appender.E.layout.ConversionPattern =%-d{yyyy-MM-dd HH\:mm\:ss}  [ %t\:%r ] - [ %p ]  %m%n 

# If programmed properly the most messages would be at DEBUG
# and the least at FATAL.
log4j.logger.org.appfuse=INFO
log4j.logger.org.appfuse.webapp.filter=ERROR
log4j.logger.org.appfuse.webapp.listener.UserCounterListener=WARN
log4j.logger.org.appfuse.util=WARN

# Print only messages of level ERROR or above in the package noModule.
log4j.logger.noModule=ERROR

# OpenSymphony Stuff
log4j.logger.com.opensymphony=INFO

# Struts2 Stuff
log4j.logger.org.apache.struts2=INFO


# Control logging for other open source packages
log4j.logger.com.ibatis.db=WARN
log4j.logger.com.opensymphony.oscache=ERROR
log4j.logger.net.sf.navigator=ERROR
log4j.logger.org.acegisecurity=WARN
log4j.logger.org.apache.commons=ERROR
log4j.logger.com.opensymphony.webwork=INFO
log4j.logger.org.displaytag=ERROR
log4j.logger.org.springframework=INFO
log4j.logger.org.apache.velocity=WARN
log4j.logger.org.tuckey.web.filters=WARN

# Enable Spring Security debug logging  WARN DEBUG ERROR
log4j.logger.org.springframework.security=ERROR

# Don't show debug logs for WebTest
log4j.logger.com.canoo.webtest=WARN
log4j.logger.com.gargoylesoftware.htmlunit=WARN

# All hibernate log output of "info" level or higher goes to stdout.
# For more verbose logging, change the "info" to "debug" on the last line.
log4j.logger.org.hibernate.ps.PreparedStatementCache=INFO
log4j.logger.org.hibernate=INFO

# Changing the log level to DEBUG will result in Hibernate generated
# SQL to be logged.
log4j.logger.org.hibernate.SQL=INFO

# Changing the log level to DEBUG will result in the PreparedStatement
# bound variable values to be logged.
log4j.logger.org.hibernate.type=INFO




