#lee.User=lee.UserConverter
#java.long.Object[]=person.daizhongde.nontaxteam.util.Struts2ValuesConverter
#lee.User=lee.UserConverter
#options=person.daizhongde.virtue.struts2.converter.TypeConverter_ExportOptions
# if config this globel converter, it will conflict with CURD action's attribute
#java.util.Map=person.daizhongde.virtue.struts2.converter.TypeConverter_ExportOptions

